### ISSUE TITLE
Can't install rest api in node 8 because of node inspector

### ISSUE THREAD

**Issue by elpibeperez** [trwalker/generator-express-rest-api#6]
Hi guys and gals,

I am testing diferent generators for express. I like yours, but when I was testing "npm run install-local" I got this error due to issues between the generator and node inspector. 

This is a clean vanilla ubuntu 17.10, I am testing various recipees using vagrant.

vagrant@ubuntu1710:~/test$ yo express-rest-api
? Application Name test
? Version 1.0.0
? Application Description 
? Author Eduardo
? Git Repository 
? License 
   create package.json
   create server.js
   create app/config/route.config.json
   create app/config/route-config.js
   create app/config/worker-config.js
   create app/config/settings/settings-config.js
   create app/config/settings/settings.config.dev.json
   create app/config/settings/settings.config.test.json
   create app/config/settings/settings.config.prod.json
   create test/mocha.opts
   create test/tests.initialize.js
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No license field.

+ body-parser@1.18.2
+ express@4.16.3
+ cluster-service@2.1.0
added 60 packages in 6.891s

> sinon@4.5.0 postinstall /home/vagrant/test/node_modules/sinon
> node scripts/support-sinon.js

Have some ❤️ for Sinon? You can support the project via Open Collective:
 > https://opencollective.com/sinon/donate

npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No license field.

+ istanbul@0.4.5
+ sinon@4.5.0
+ chai@4.1.2
+ mocha@5.1.1
added 92 packages in 9.433s
vagrant@ubuntu1710:~/test$ npm run install-local

> test@1.0.0 install-local /home/vagrant/test
> npm install -g mocha & npm install -g node-inspector & npm install

/home/vagrant/.npm-global/bin/_mocha -> /home/vagrant/.npm-global/lib/node_modules/mocha/bin/_mocha
/home/vagrant/.npm-global/bin/mocha -> /home/vagrant/.npm-global/lib/node_modules/mocha/bin/mocha
+ mocha@5.1.1
added 24 packages in 2.95s
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No license field.

added 6 packages in 3.394s

> v8-profiler@5.7.0 preinstall /home/vagrant/.npm-global/lib/node_modules/node-inspector/node_modules/v8-profiler
> node -e 'process.exit(0)'

> v8-debug@1.0.1 preinstall /home/vagrant/.npm-global/lib/node_modules/node-inspector/node_modules/v8-debug
> node -e 'process.exit(0)'

/home/vagrant/.npm-global/bin/node-debug -> /home/vagrant/.npm-global/lib/node_modules/node-inspector/bin/node-debug.js
/home/vagrant/.npm-global/bin/node-inspector -> /home/vagrant/.npm-global/lib/node_modules/node-inspector/bin/inspector.js

> v8-debug@1.0.1 install /home/vagrant/.npm-global/lib/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v57-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@1.0.1 and node@8.11.1 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
make: Entering directory '/home/vagrant/.npm-global/lib/node_modules/node-inspector/node_modules/v8-debug/build'
  CXX(target) Release/obj.target/debug/src/debug.o
make: g++: Command not found
debug.target.mk:98: recipe for target 'Release/obj.target/debug/src/debug.o' failed
make: *** [Release/obj.target/debug/src/debug.o] Error 127
make: Leaving directory '/home/vagrant/.npm-global/lib/node_modules/node-inspector/node_modules/v8-debug/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.13.0-38-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/vagrant/.npm-global/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v57-linux-x64/debug.node" "--module_name=debug" "--module_path=/home/vagrant/.npm-global/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v57-linux-x64"
gyp ERR! cwd /home/vagrant/.npm-global/lib/node_modules/node-inspector/node_modules/v8-debug
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/vagrant/.npm-global/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v57-linux-x64/debug.node --module_name=debug --module_path=/home/vagrant/.npm-global/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v57-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/vagrant/.npm-global/lib/node_modules/node-inspector/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.13.0-38-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/vagrant/.npm-global/lib/node_modules/node-inspector/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/vagrant/.npm-global/lib/node_modules/node-inspector/node_modules/v8-debug
node-pre-gyp ERR! node -v v8.11.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/vagrant/.npm-global/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v57-linux-x64/debug.node --module_name=debug --module_path=/home/vagrant/.npm-global/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v57-linux-x64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-debug@1.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@1.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2018-04-26T19_31_56_787Z-debug.log
^C
vagrant@ubuntu1710:~/test$ npm install -g node-inspector

> v8-profiler@5.7.0 preinstall /home/vagrant/.npm-global/lib/node_modules/node-inspector/node_modules/v8-profiler
> node -e 'process.exit(0)'

> v8-debug@1.0.1 preinstall /home/vagrant/.npm-global/lib/node_modules/node-inspector/node_modules/v8-debug
> node -e 'process.exit(0)'

/home/vagrant/.npm-global/bin/node-inspector -> /home/vagrant/.npm-global/lib/node_modules/node-inspector/bin/inspector.js
/home/vagrant/.npm-global/bin/node-debug -> /home/vagrant/.npm-global/lib/node_modules/node-inspector/bin/node-debug.js

> v8-debug@1.0.1 install /home/vagrant/.npm-global/lib/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v57-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@1.0.1 and node@8.11.1 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
make: Entering directory '/home/vagrant/.npm-global/lib/node_modules/node-inspector/node_modules/v8-debug/build'
  CXX(target) Release/obj.target/debug/src/debug.o
make: g++: Command not found
debug.target.mk:98: recipe for target 'Release/obj.target/debug/src/debug.o' failed
make: *** [Release/obj.target/debug/src/debug.o] Error 127
make: Leaving directory '/home/vagrant/.npm-global/lib/node_modules/node-inspector/node_modules/v8-debug/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.13.0-38-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/vagrant/.npm-global/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v57-linux-x64/debug.node" "--module_name=debug" "--module_path=/home/vagrant/.npm-global/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v57-linux-x64"
gyp ERR! cwd /home/vagrant/.npm-global/lib/node_modules/node-inspector/node_modules/v8-debug
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/vagrant/.npm-global/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v57-linux-x64/debug.node --module_name=debug --module_path=/home/vagrant/.npm-global/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v57-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/vagrant/.npm-global/lib/node_modules/node-inspector/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.13.0-38-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/vagrant/.npm-global/lib/node_modules/node-inspector/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/vagrant/.npm-global/lib/node_modules/node-inspector/node_modules/v8-debug
node-pre-gyp ERR! node -v v8.11.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/vagrant/.npm-global/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v57-linux-x64/debug.node --module_name=debug --module_path=/home/vagrant/.npm-global/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v1.0.1/node-v57-linux-x64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-debug@1.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@1.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2018-04-26T19_36_51_082Z-debug.log

**Comment by jmog1994** [comment]
Hi man,
I had the same issue than you had... I would like to know how did you handle it, I work around it by installing another stable version of node inspector by running:
`npm install -g node-inspector@0.7.5`
I got that info from this page https://github.com/node-inspector/node-inspector/issues/976
good luck!
